#!/bin/sh
# set -e

# ScraperWiki boxes

# Settings
. ~/.boxrc
boxname="$1"

# Create and add key
curl --data apikey="$apikey" http://ds.scraperwiki.com/scraperwiki/"$boxname"
curl --data-urlencode sshkey@$(printf ~/.ssh/id_[rd]sa.pub) --data apikey="$apikey" http://ds.scraperwiki.com/scraperwiki/"$boxname"/sshkeys
ssh scraperwiki.${boxname}@box.scraperwiki.com "printf '[receive]\n\tdenyCurrentBranch = ignore\n' >> ~/.git/config"
echo Run this.
echo "git clone 'scraperwiki.${boxname}@box.scraperwiki.com:.git' ${boxname}"
