#!/bin/bash
set -e

if [ ! -d "${HOME}/.dotfiles/private" ] || [ ! -d "${HOME}/.dotfiles/public" ] ; then
  echo Dotfiles must be stored in the ~/.dotfiles/{private,public} directories.
  exit 1
fi

for dotfiles_dir in ~/.dotfiles/private ~/.dotfiles/public; do
  (
    cd "${dotfiles_dir}"
    for dotfile in .*; do
      [ "${dotfile}" = '.' ] && continue
      [ "${dotfile}" = '..' ] && continue
      ln -s "${dotfiles_dir}/${dotfile}" ~/"${dotfile}"
    done
  )
done
