#!/bin/bash

# Count how many pages are in the passed PDF then
# select a number randomly. This is useful for
# creating fixtures when doing things with PDFs.

# For storing pdfinfo output
tmp=$(mktemp)

# Check if it's a pdf
if
  pdfinfo "$1" 1> $tmp 2> /dev/null
  grep 'Pages:' $tmp > /dev/null
then
  # Select a random page number
  npages=$(sed -n '/Pages:/ s/[^0-9]//gp' $tmp)
  echo $((($RANDOM % $npages) + 1))
  exitcode=0
else
  # Not a pdf
  echo Not a pdf
  exitcode=1
fi

rm $tmp
exit $exitcode
