#!/bin/sh

# Search university LDAP directories.
# I started with Ivy League because it's small.

school=$(echo "$1" | tr '[A-Z]' '[a-z'])
name="$2"

# LDAP
ldap() {
  b="$1"
  hostname="$2"
  ldap_field="$3"
  [ -z "$ldap_field" ] && ldap_field=cn
  mkdir -p ~/log
  ldapsearch -h "$hostname" -s sub -b "$b" -x -t -LLL "(&($ldap_field=*$name*))" 2>> ~/log/ldap-error.log
}

# These require authentication
# Brown University 
# University of Pennsylvania http://www.upenn.edu/computing/help/doc/email/directory.html

# Some nice documents
# http://wiki.itec.suny.edu/download/attachments/7114623/SUNYCampusPersonSpecv2.6.1.pdf?version=1&modificationDate=1343134795000

# Commented cases don't work.

case "$school" in
  # Ivy League
  col|columbia) ldap 'o=Columbia University,c=US' ldap.columbia.edu ;;
  cor|cornell) ldap 'o=Cornell University,c=US' directory.cornell.edu ;;
  d|dartmouth) ldap 'dc=dartmouth,dc=edu' dnd.dartmouth.edu ;;
  h|harvard) ldap 'o=Harvard University,c=US' phonebook.harvard.edu ;;
  p|princeton) ldap 'o=Princeton University,c=US' ldap.princeton.edu ;;
  y|yale) ldap 'o=yale.edu' directory.yale.edu ;;


  # Largest universities
  # http://en.wikipedia.org/wiki/List_of_United_States_university_campuses_by_enrollment
# osu|ohio) ldap 'o=OSU Directory,ou=People,dc=osu,dc=edu' directory.service.ohio-state.edu ;;
  umn|minnesota) ldap 'o=University of Minnesota,c=US' ldap.umn.edu ;;
  ut|austin|utexas) ldap 'dc=directory,dc=utexas,dc=edu' directory.utexas.edu ;;
  gw|georgewashington) ldap 'o=gmu.edu' directory.gmu.edu ;;
# nyu) ldap 'o=New York University,st=New York,c=US' ldap.nyu.edu ;;
#   http://www.cns.nyu.edu/help/osx/NYU_LDAP
# bu|boston) ldap 'o=Boston University,c=US' ldap.bu.edu ;;

  *) echo "usage: $0 <school> <person's name>"
esac
