#!/bin/sh

school="$1"
name="$2"

# LDAP
ldap() {
  hostname="$1"
  ldap_name="$2"
  ldapsearch -h "$hostname" -s sub -b "o=$ldap_name,c=US" -x -t -LLL "(&(displayName=*$name*))"
} tr , '\n'|grep "$name" ||


ldap Cornell\ University directory.cornell.edu|grep @ ||
# Princeton's LDAP service
ldap Princeton\ University ldap.princeton.edu|grep @
# Dartmounth
ldap Dartmouth\ College ldap.dartmouth.edu
